export const greaterAustinServiceAreas = [
  'Austin',
  'West Lake Hills',
  'Rollingwood',
  'Tarrytown',
  'Northwest Hills',
  'West Lake Highlands',
  'Lakeway',
  'Bee Cave',
  'Lake Travis',
  'Steiner Ranch',
  'Barton Creek',
  'Circle C Ranch',
  'Pemberton Heights',
  'Old West Austin',
  'Clarksville',
  'Allandale',
  'Crestview',
  'Leander',
  'Georgetown',
  'Round Rock',
  'Cedar Park',
  'North Austin'
] as const;
