/**
 * Route Configuration
 *
 * Re-exports route data from routeData.mjs for TypeScript consumers.
 * The canonical source of truth is routeData.mjs.
 */

export {
  BASE_URL,
  geoAreas,
  serviceLocationPages,
  coreStaticRoutes,
  getStaticRoutes,
  getGeoRoutes,
  getAllRoutes,
  getAllRoutePaths,
  getServiceLocationPaths
} from './routeData.mjs';

export const staticRoutes = [
  { path: '/', changefreq: 'weekly', priority: '1.0' },
  { path: '/about', changefreq: 'monthly', priority: '0.8' },
  { path: '/services', changefreq: 'weekly', priority: '0.9' },
  { path: '/services/interior-painting', changefreq: 'monthly', priority: '0.8' },
  { path: '/services/exterior-painting', changefreq: 'monthly', priority: '0.8' },
  { path: '/services/cabinet-refinishing', changefreq: 'monthly', priority: '0.8' },
  { path: '/services/commercial', changefreq: 'monthly', priority: '0.7' },
  { path: '/gallery', changefreq: 'weekly', priority: '0.7' },
  { path: '/testimonials', changefreq: 'weekly', priority: '0.7' },
  { path: '/faq', changefreq: 'monthly', priority: '0.7' },
  { path: '/service-areas', changefreq: 'monthly', priority: '0.9' },
  { path: '/service-areas/austin', changefreq: 'monthly', priority: '0.9' },
  { path: '/service-areas/tarrytown', changefreq: 'monthly', priority: '0.8' },
  { path: '/service-areas/northwest-hills', changefreq: 'monthly', priority: '0.8' },
  { path: '/service-areas/west-lake-hills', changefreq: 'monthly', priority: '0.8' },
  { path: '/service-areas/west-lake-highlands', changefreq: 'monthly', priority: '0.8' },
  { path: '/service-areas/lakeway', changefreq: 'monthly', priority: '0.8' },
  { path: '/service-areas/leander', changefreq: 'monthly', priority: '0.8' },
  { path: '/service-areas/georgetown', changefreq: 'monthly', priority: '0.8' },
  { path: '/service-areas/round-rock', changefreq: 'monthly', priority: '0.8' },
  { path: '/service-areas/cedar-park', changefreq: 'monthly', priority: '0.8' },
  { path: '/service-areas/north-austin', changefreq: 'monthly', priority: '0.8' },
  { path: '/color-consultation', changefreq: 'monthly', priority: '0.7' },
  { path: '/contact', changefreq: 'monthly', priority: '0.9' },
  { path: '/blog', changefreq: 'weekly', priority: '0.8' },
  { path: '/guides/painting-costs-austin', changefreq: 'monthly', priority: '0.7' },
  { path: '/guides/best-paint-texas-heat', changefreq: 'monthly', priority: '0.7' },
  { path: '/guides/hoa-color-tips-austin', changefreq: 'monthly', priority: '0.7' },
  { path: '/guides/how-often-paint-central-texas', changefreq: 'monthly', priority: '0.7' },
  { path: '/financing', changefreq: 'monthly', priority: '0.7' },
  { path: '/privacy', changefreq: 'yearly', priority: '0.3' },
  { path: '/terms', changefreq: 'yearly', priority: '0.3' },
  { path: '/do-not-sell', changefreq: 'yearly', priority: '0.3' },
  { path: '/interior-painting-austin', changefreq: 'monthly', priority: '0.8' },
  { path: '/interior-painting-tarrytown', changefreq: 'monthly', priority: '0.8' },
  { path: '/interior-painting-northwest-hills', changefreq: 'monthly', priority: '0.8' },
  { path: '/interior-painting-west-lake-hills', changefreq: 'monthly', priority: '0.8' },
  { path: '/interior-painting-west-lake-highlands', changefreq: 'monthly', priority: '0.8' },
  { path: '/interior-painting-lakeway', changefreq: 'monthly', priority: '0.8' },
  { path: '/exterior-painting-austin', changefreq: 'monthly', priority: '0.8' },
  { path: '/exterior-painting-tarrytown', changefreq: 'monthly', priority: '0.8' },
  { path: '/exterior-painting-northwest-hills', changefreq: 'monthly', priority: '0.8' },
  { path: '/exterior-painting-west-lake-hills', changefreq: 'monthly', priority: '0.8' },
  { path: '/exterior-painting-west-lake-highlands', changefreq: 'monthly', priority: '0.8' },
  { path: '/exterior-painting-lakeway', changefreq: 'monthly', priority: '0.8' },
  { path: '/cabinet-refinishing-austin', changefreq: 'monthly', priority: '0.8' },
  { path: '/cabinet-refinishing-tarrytown', changefreq: 'monthly', priority: '0.8' },
  { path: '/cabinet-refinishing-northwest-hills', changefreq: 'monthly', priority: '0.8' },
  { path: '/cabinet-refinishing-west-lake-hills', changefreq: 'monthly', priority: '0.8' },
  { path: '/cabinet-refinishing-west-lake-highlands', changefreq: 'monthly', priority: '0.8' },
  { path: '/cabinet-refinishing-lakeway', changefreq: 'monthly', priority: '0.8' },
  { path: '/commercial-painting-austin', changefreq: 'monthly', priority: '0.8' },
  { path: '/commercial-painting-tarrytown', changefreq: 'monthly', priority: '0.8' },
  { path: '/commercial-painting-northwest-hills', changefreq: 'monthly', priority: '0.8' },
  { path: '/commercial-painting-west-lake-hills', changefreq: 'monthly', priority: '0.8' },
  { path: '/commercial-painting-west-lake-highlands', changefreq: 'monthly', priority: '0.8' },
  { path: '/commercial-painting-lakeway', changefreq: 'monthly', priority: '0.8' },
];

export const serviceRedirectPatterns = [
  { pattern: /^\/residential-interior-/, target: '/services/interior-painting' },
  { pattern: /^\/residential-exterior-/, target: '/services/exterior-painting' },
  { pattern: /^\/residential-cabinet-/, target: '/services/cabinet-refinishing' },
  { pattern: /^\/commercial-.*-painting/, target: '/services/commercial' },
  { pattern: /^\/commercial-interior-/, target: '/services/commercial' },
  { pattern: /^\/industrial-/, target: '/services/commercial' },
  { pattern: /^\/hotel-/, target: '/services/commercial' },
  { pattern: /^\/residential-(fence|deck|porch|garage|stucco)-/, target: '/services' },
  { pattern: /^\/service\//, target: '/services' },
];

export const locationRedirectPatterns = [
  { pattern: /tarrytown/i, target: '/service-areas/tarrytown' },
  { pattern: /northwest-hills/i, target: '/service-areas/northwest-hills' },
  { pattern: /west-lake-hills/i, target: '/service-areas/west-lake-hills' },
  { pattern: /west-lake-highlands/i, target: '/service-areas/west-lake-highlands' },
  { pattern: /lakeway/i, target: '/service-areas/lakeway' },
  { pattern: /leander/i, target: '/service-areas/leander' },
  { pattern: /georgetown/i, target: '/service-areas/georgetown' },
  { pattern: /round-rock/i, target: '/service-areas/round-rock' },
  { pattern: /cedar-park/i, target: '/service-areas/cedar-park' },
  { pattern: /north-austin/i, target: '/service-areas/north-austin' },
];
