- name: Mirror to ScaleSmall/hillcosite
  run: |
    git config --global user.email "action@github.com"
    git config --global user.name "GitHub Action"
    git remote add mirror https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/ScaleSmall/hillcosite.git
    git push mirror main --force
  env:
   GIT_TRACE: 1
